# Generated by Django 3.0.7 on 2020-06-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paints',
            new_name='Paint',
        ),
    ]
