# Generated by Django 3.0.7 on 2020-06-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200621_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.FileField(default=1, upload_to=''),
        ),
    ]
