# Generated by Django 3.0.7 on 2020-06-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200621_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('userDescription', models.TextField()),
                ('userImage', models.FileField(upload_to='')),
            ],
        ),
    ]
